# Generated by Django 5.1.3 on 2024-12-05 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_and_permission', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
